STYLE: Prefer using `https` instead of `http` in copyright notice
Prefer using `https` instead of `http` in copyright notice license link.

Changed in InsightSoftwareConsortium/ITK#3428

Fixes:
```
/home/runner/work/ITKPolarTransform/ITKPolarTransform/include/itkCartesianToPolarTransform.h:9:
 error: Header mismatch:
 ://www.apache.org/licenses/LICENSE-2.0.txt (s://www.apache.org/licenses/LICENSE-2.0.txt) : Utilities/KWStyle/ITKHeader.h
/home/runner/work/ITKPolarTransform/ITKPolarTransform/include/itkCartesianToPolarTransform.hxx:9:
 error: Header mismatch:
 ://www.apache.org/licenses/LICENSE-2.0.txt (s://www.apache.org/licenses/LICENSE-2.0.txt) : Utilities/KWStyle/ITKHeader.h
/home/runner/work/ITKPolarTransform/ITKPolarTransform/include/itkPolarToCartesianTransform.h:9:
 error: Header mismatch:
 ://www.apache.org/licenses/LICENSE-2.0.txt (s://www.apache.org/licenses/LICENSE-2.0.txt) : Utilities/KWStyle/ITKHeader.h
/home/runner/work/ITKPolarTransform/ITKPolarTransform/include/itkPolarToCartesianTransform.hxx:9:
 error: Header mismatch:
 ://www.apache.org/licenses/LICENSE-2.0.txt (s://www.apache.org/licenses/LICENSE-2.0.txt) : Utilities/KWStyle/ITKHeader.h
/home/runner/work/ITKPolarTransform/ITKPolarTransform/test/itkPolarTransformTest.cxx:9:
 error: Header mismatch:
 ://www.apache.org/licenses/LICENSE-2.0.txt (s://www.apache.org/licenses/LICENSE-2.0.txt) : Utilities/KWStyle/ITKHeader.h
```

raised for example in:
https://github.com/InsightSoftwareConsortium/ITKPolarTransform/actions/runs/13094200407/job/36534462910#step:14:60